queue: FSX

variables:
    BuildPlatform: Any CPU
    BuildConfiguration: Release

steps:

- task: gittools.gitversion.gitversion-task.GitVersion@3

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.x
  inputs:
      versionSpec: 4.x
      checkLatest: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: AspNetClassicSessionState.sln
    vstsFeed: '74a5a491-5c25-48f8-a89a-00d9eded165b'

- task: VSBuild@1
  displayName:  Visual Studio Build
  inputs:
    solution: AspNetClassicSessionState.sln
    vsVersion: 15.0
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
    maximumCpuCount: true
    msbuildArchitecture: x64
    msbuildArgs: /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\AspNetClassicSessionState /p:PackageVersion=$(GitVersion.NuGetVersion) /p:AssemblyVersion=$(GitVersion.AssemblySemVer)
    
- task: VSTest@2
  displayName: Run Unit Tests
  inputs:
    testSelector: testAssemblies
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    vsTestVersion: 15.0
    otherConsoleOptions: /platform:x64
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
    runInParallel: true
    codeCoverageEnabled: true
    publishRunAttachments: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: AspNetClassicSessionState NuGet'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\AspNetClassicSessionState
    artifactType: container
    artifactName: AspNetClassicSessionState
